name: Stats

on:
  push:
    branches: [ main ]
jobs:
  build:
      runs-on: ubuntu-latest

      permissions:
        contents: write
      
      steps:
          - name: Checkout Repo - get access
            uses: actions/checkout@v4
            
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Install libraries
            run: pip install requests pandas lxml html5lib beautifulsoup4 #brotli

          - name: Set environment to use UTF-8
            run: |
              sudo update-locale LANG=en_US.UTF-8
              export PYTHONIOENCODING=utf-8
              
          - name: Run script
            run: python main.py #./CARPETA/main.py
            
          # - name: Commit and push results
          # run: |
          #   git config --global user.name "GitHub Actions"
          #   git config --global user.email "actions@github.com"
          #   git add <ruta_del_archivo_generado>
          #   git commit -m "Añadir resultados generados por el script"
          #   git push
          # env:
          #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Commit and Push changes
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
              commit_message: UPDATE RESULT FILES
              commit_user_name: Brais Moure [GitHub Actions]
              commit_user_email: carsiro96.ittools@hotmail.com
              commit_author: carsiro96.ittools@hotmail.com
        
