name: Stats

on:
  push:
    branches: [ main ]
jobs:
  build:
      runs-on: ubuntu-latest

      permissions:
        contents: write
      
      steps:
          - name: Checkout Repo - get access
            uses: actions/checkout@v4
            
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Install libraries
            run: pip install requests
            
          - name: Run script
            run: python main.py #./Roadmap/main.py

          - name: Commit and Push changes
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
              commit_message: UPDATE RESULT FILES
              commit_user_name: Brais Moure [GitHub Actions]
              commit_user_email: carsiro96.ittools@hotmail.com
              commit_author: CARSIRO96it
        
